dbt_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: p_source_db
      schema: p_source_schema
      warehouse: compute_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: p_mart
      schema: p_mart_schema
      warehouse: compute_wh