SELECT
	  TO_CHAR(DATE_TRUNC('MONTH', c.START_DATE), 'YYYY-MM') AS MONTH
	, SUM(p.COST)    AS TOTAL_COST
	, SUM(p.REVENUE) AS TOTAL_REVENUE
FROM ref {{ 'CAMPAIGN_PERFORMANCE' }} p
JOIN ref {{ 'P_CAMPAIGNS' }} c
  ON p.CAMPAIGN_ID = c.CAMPAIGN_ID
GROUP BY 1
ORDER BY 1