## Project
name: DBT_Chart_2
version: "1.0"
config-version: 2
profile: DBT_Chart_2

## Sources
model-paths: [models]
test-paths: [tests]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  DBT_Chart_2:
    staging:
      +materialized: view
    marts:
      +materialized: table
