name: DBT_Chart_3
version: 1.0.0
config-version: 2
profile: DBT_Chart_3
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  DBT_Chart_3:
    +materialized: view
