DBT_Chart_3:
  target: prd
  outputs:
    prd:
      type: snowflake
      account: yz80908
      user: SEONGCHEON_NA
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: P_MART
      schema: P_MART_SCHEMA
